swagger: "2.0"
info:
  description: Quake 3 arena's game log API
  version: "1.0.0"
  title: Swagger quake log API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /games:
    get:
      operationId: controller.games.list_all
      tags:
        - Games
      summary: List all games
      description: List all games presented in the log file
      responses:
        200:
          description: Successfully list games from log file
          schema:
            type: array
            items:
              properties:
                game:
                  type: string
                total_kills:
                  type: integer
                players:
                  type: array
                kills:
                  type: object      

  /game/{game_number}:
    get:
      operationId: controller.games.get_game
      tags:
        - Games
      summary: Get one game from the game list
      description: Get one game, in ocuurence order, from the log file
      parameters:
        - name: game_number
          in: query
          type: integer
          description: Game number in occurence order
          required: true
      responses:
        200:
          description: Successfully get game 
          schema:
            properties:
              game:
                type: string
              total_kills:
                type: integer
              players:
                type: array
              kills:
                type: object
        404:
          description: Game number not found
          schema:
            type: object
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string