swagger: "2.0"
info:
  description: Quake 3 arena's game log API
  version: "1.0.0"
  title: Swagger quake log API
consumes:
  - application/json
produces:
  - application/json

basePath: /api

paths:
  /games/{file_name}:
    get:
      operationId: controller.game_controller.list_all
      tags:
        - Games
      summary: List all games
      description: List all games presented in the log file
      parameters:
        - name: file_name
          in: query
          type: string
          description: Name of the log file (file.log)
          required: true
      responses:
        200:
          description: Successfully list games from log file
          schema:
            type: array
            items:
              properties:
                game_1:
                  type: object
                  properties:
                    total_kills:
                      type: integer
                    players:
                      type: array
                      items:
                        type: string
                    kills:
                      type: object
                      properties:
                        string:
                          type: integer 
                    alert_messages:
                      type: array
                      items:
                        type: string    

        404:
          description: File not found
          schema:
            type: object
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string

  /game/{file_name}/{game_number}:
    get:
      operationId: controller.game_controller.get_game
      tags:
        - Games
      summary: Get one game from the game list
      description: Get one game, in ocuurence order, from the log file
      parameters:
        - name: file_name
          in: query
          type: string
          description: Name of the log file (file.log)
          required: true
        - name: game_number
          in: query
          type: integer
          description: Game number in occurence order
          required: true
      responses:
        200:
          description: Successfully get game 
          schema:
              properties:
                game_1:
                  type: object
                  properties:
                    total_kills:
                      type: integer
                    players:
                      type: array
                      items:
                        type: string
                    kills:
                      type: object
                      properties:
                        string:
                          type: integer 
                    alert_messages:
                      type: array
                      items:
                        type: string    

        404:
          description: Game number not found or File not found 
          schema:
            type: object
            properties:
              detail:
                type: string
              status:
                type: integer
              title:
                type: string
              type:
                type: string